CREATE TABLE actTransaction (
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 )PRIMARY KEY NOT NULL,
donarName VARCHAR(100) NOT NULL,
paymentDate DATE NOT NULL,
paymentNo INTEGER NOT NULL,
amount DOUBLE NOT NULL
);


' insert into actTransaction(donarName, paymentDate,paymentNo,amount)  values  ('test', now(), 1, 12.25);