--hsqldb ddl
CREATE SCHEMA mwamba;
CREATE user mwamba password '';

CREATE TABLE mwamba.actTransaction (
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 )PRIMARY KEY NOT NULL,
donarName VARCHAR(100) NOT NULL,
paymentDate DATE NOT NULL,
paymentNo INTEGER NOT NULL,
amount DOUBLE NOT NULL
);

-- mysql ddl
DROP TABLE donation;
DROP TABLE donor;

CREATE TABLE donor (
id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
address1 VARCHAR(100) NOT NULL,
address2 VARCHAR(100) NOT NULL,
city VARCHAR(50) NOT NULL,
state VARCHAR(2) NOT NULL,
zip VARCHAR(10) NOT NULL,
phone VARCHAR(16),
email VARCHAR(255),
notes VARCHAR(255),
PRIMARY KEY (`id`),
UNIQUE KEY `nameKey`(name)
);

CREATE TABLE donation (
id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
donorId bigint(20) unsigned NOT NULL,
paymentDate DATE NOT NULL,
paymentNo INTEGER NOT NULL,
amount DOUBLE NOT NULL,
description VARCHAR(200),
PRIMARY KEY (`id`),
UNIQUE KEY `paymentNoKey`(paymentNo),
FOREIGN KEY (donorId) 
        REFERENCES donor(id)
        ON DELETE CASCADE
);